#!/bin/bash

APPID=24358ee068d1f33b66181473b2f04159
mode=json
q=$1
units=$2
forecast=$3

if [ ${q} == "-o"  ] && [ ${forecast} == "-n" ];
then
	
	myIP=$(curl -s "https://ipinfo.io/ip")
	geoInfo=$(curl -s "https://ipinfo.io/${myIP}/geo")
	
	city=$(jq '.city' <<< ${geoInfo} | tr -d '"')
	country=$(jq '.country' <<< ${geoInfo} | tr -d '"')
	zip=$(jq '.postal' <<< ${geoInfo} | tr -d '"')
	
	q="${city},${country}"
		
	echo "Current Temperature in ${city}, ${country}"

	if [[ ${units} == "-c" ]];
	then

		units=metric
		weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
		ending="°C"
		
	elif [[ ${units} == "-f" ]];
	then

		units=imperial
		weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
		ending="°F"
	
	else
				
		weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&mode=${mode}&APPID=${APPID}"
		ending=" K"	
	
	fi

	weatherInfo=$(curl -s ${weatherURL})
	temp=$(jq '.main.temp' <<< ${weatherInfo})
	descrp=$(jq '.weather[0].description' <<< ${weatherInfo} | tr -d '"')
		
	echo ${temp}${ending}
	echo ${descrp}


elif [[ ${forecast} == "-n" ]];
then
	
	echo "Current Temperature in ${city}, ${country}"

	if [[ ${units} == "-c" ]];
	then
		units=metric
		weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
		temp=$(curl -s ${weatherURL} | jq '.main.temp')
		descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
		echo ${temp}°C
		echo ${descrp}

	elif [[ ${units} == "-f" ]];
	then
			units=imperial
			weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
			temp=$(curl -s ${weatherURL} | jq '.main.temp')
			descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
			echo ${temp}°F
			echo ${descrp}

	else
		
		weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&mode=${mode}&APPID=${APPID}"
		temp=$(curl -s ${weatherURL} | jq '.main.temp')
		descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
		echo ${temp} K
		echo ${descrp}

	fi

elif [ ${q} == "-h"  ] && [ ${forecast} == "-m" ];
then
	
	myIP=$(curl -s "https://ipinfo.io/ip")
	geoInfo=$(curl -s "https://ipinfo.io/${myIP}/geo")
	city=$(curl -s "https://ipinfo.io/${myIP}/geo" | jq '.city' | tr -d '"')
	country=$(curl -s "https://ipinfo.io/${myIP}/geo" | jq '.country' | tr -d '"')
	zip=$(curl -s "https://ipinfo.io/${myIP}/geo" | jq '.postal' | tr -d '"')
	q="${city},${country}"
	
	echo "Current Temperature in ${city}, ${country}"

	if [[ ${units} == "-c" ]];
	then
		units=metric
		weatherURL="https://api.openweathermap.org/data/2.5/forecast?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
		
		curl -s ${weatherURL} | jq -c '.list[]' | while read info; do
			echo ${info} | jq '.dt_txt' | tr -d '"'
			echo ${info} | jq '.main.temp' 
			echo ${info} | jq '.weather[0].description' | tr -d '"'
			echo
		done

	elif [[ ${units} == "-f" ]];
	then

		units=imperial
		weatherURL="https://api.openweathermap.org/data/2.5/forecast?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
		temp=$(curl -s ${weatherURL} | jq '.main.temp')
		descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
		echo ${temp}°F
		echo ${descrp}
	
	else
		
		weatherURL="https://api.openweathermap.org/data/2.5/forecast?zip=${zip},${country}&mode=${mode}&APPID=${APPID}"
		temp=$(curl -s ${weatherURL} | jq '.main.temp')
		descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
		echo ${temp} K
		echo ${descrp}
	
	fi

elif [[ ${forecast} == "-m" ]];
then
	
	echo "Current Temperature in ${city}, ${country}"

	if [[ ${units} == "-c" ]];
	then
		units=metric
		weatherURL="https://api.openweathermap.org/data/2.5/forecast?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
		temp=$(curl -s ${weatherURL} | jq '.main.temp')
		descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
		echo ${temp}°C
		echo ${descrp}

	elif [[ ${units} == "-f" ]];
	then
			units=imperial
			weatherURL="https://api.openweathermap.org/data/2.5/forecast?zip=${zip},${country}&units=${units}&mode=${mode}&APPID=${APPID}"
			temp=$(curl -s ${weatherURL} | jq '.main.temp')
			descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
			echo ${temp}°F
			echo ${descrp}

	else
		
		weatherURL="https://api.openweathermap.org/data/2.5/weather?zip=${zip},${country}&mode=${mode}&APPID=${APPID}"
		temp=$(curl -s ${weatherURL} | jq '.main.temp')
		descrp=$(curl -s ${weatherURL} | jq '.weather[0].description' | tr -d '"')
		
		echo ${temp} K
		echo ${descrp}

	fi
fi
